spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YashwanthRachepalli/config-repo
          search-paths:
            - ams
          default-label: master
        bootstrap: true
  management:
    security:
      enabled: false

server:
  port: 8888
